#!/usr/bin/env bash
#
# openM++ build script.
# you can customize this script or any scripts below in order to change build results

set -e

./build-openm && \
./build-models && \
./build-go && \
./build-ui && \
./build-tar-xz
